// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: arithmetic.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Math.ArithmeticServices {
  public static partial class ArithmeticService
  {
    static readonly string __ServiceName = "ArithmeticServices.ArithmeticService";

    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    static readonly grpc::Marshaller<global::Math.ArithmeticServices.InputRequest> __Marshaller_ArithmeticServices_InputRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Math.ArithmeticServices.InputRequest.Parser));
    static readonly grpc::Marshaller<global::Math.ArithmeticServices.InputResponse> __Marshaller_ArithmeticServices_InputResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Math.ArithmeticServices.InputResponse.Parser));

    static readonly grpc::Method<global::Math.ArithmeticServices.InputRequest, global::Math.ArithmeticServices.InputResponse> __Method_PerformAddOperation = new grpc::Method<global::Math.ArithmeticServices.InputRequest, global::Math.ArithmeticServices.InputResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "PerformAddOperation",
        __Marshaller_ArithmeticServices_InputRequest,
        __Marshaller_ArithmeticServices_InputResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Math.ArithmeticServices.ArithmeticReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of ArithmeticService</summary>
    [grpc::BindServiceMethod(typeof(ArithmeticService), "BindService")]
    public abstract partial class ArithmeticServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Math.ArithmeticServices.InputResponse> PerformAddOperation(global::Math.ArithmeticServices.InputRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for ArithmeticService</summary>
    public partial class ArithmeticServiceClient : grpc::ClientBase<ArithmeticServiceClient>
    {
      /// <summary>Creates a new client for ArithmeticService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public ArithmeticServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for ArithmeticService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public ArithmeticServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected ArithmeticServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected ArithmeticServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Math.ArithmeticServices.InputResponse PerformAddOperation(global::Math.ArithmeticServices.InputRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return PerformAddOperation(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Math.ArithmeticServices.InputResponse PerformAddOperation(global::Math.ArithmeticServices.InputRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_PerformAddOperation, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Math.ArithmeticServices.InputResponse> PerformAddOperationAsync(global::Math.ArithmeticServices.InputRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return PerformAddOperationAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Math.ArithmeticServices.InputResponse> PerformAddOperationAsync(global::Math.ArithmeticServices.InputRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_PerformAddOperation, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override ArithmeticServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new ArithmeticServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(ArithmeticServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_PerformAddOperation, serviceImpl.PerformAddOperation).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, ArithmeticServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_PerformAddOperation, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Math.ArithmeticServices.InputRequest, global::Math.ArithmeticServices.InputResponse>(serviceImpl.PerformAddOperation));
    }

  }
}
#endregion
